test:
  #临时灰度环境
  base_url: "http://dap-staging-6.micro-stage.lilith.sh"

  auth:
    username: dap内部自动化测试
    password: 20250624@lilith

  browser:
    type: "chromium"
    headless: false
    no_viewport: true
    slow_mo: 0